import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import terser from '@rollup/plugin-terser';

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "src/plugin/main.ts",
  output: {
    dir: "./dist",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: [
    "obsidian",
    "@codemirror/state",
    "@codemirror/view",
    "@codemirror/language",
    "@codemirror/autocomplete",
    "@codemirror/commands",
    "@codemirror/search",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  plugins: [
    // Rollup 4's @rollup/plugin-typescript requires rootDir/outDir to line up
    // with the output `dir`; keep them here rather than in tsconfig so the
    // `tsc --noEmit` typecheck script stays emit-agnostic.
    typescript({ rootDir: "src", outDir: "./dist" }),
    nodeResolve({
      browser: true,
    }),
    commonjs({ include: "node_modules/**" }),
    terser(),
  ],
};
